# Generated by Django 3.1 on 2022-04-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20220409_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdoc',
            old_name='_file',
            new_name='file',
        ),
    ]
