# Generated by Django 3.1 on 2022-04-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20220409_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydoc',
            old_name='_file',
            new_name='file',
        ),
    ]
