# Generated by Django 3.1 on 2022-04-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20220425_1339'),
        ('document', '0005_auto_20220411_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='client_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='properties.client'),
        ),
        migrations.AlterField(
            model_name='propertydoc',
            name='property_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
