# Generated by Django 3.1 on 2022-04-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20220425_1405'),
        ('document', '0006_auto_20220425_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.client'),
        ),
        migrations.AlterField(
            model_name='propertydoc',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
