# Generated by Django 3.1 on 2022-04-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20220425_1405'),
        ('document', '0007_auto_20220425_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='client_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='properties.client'),
        ),
        migrations.AlterField(
            model_name='propertydoc',
            name='property_id',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
    ]
