# Generated by Django 3.1 on 2022-04-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0008_auto_20220412_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('attached_property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='properties.property')),
            ],
        ),
    ]
