# Generated by Django 3.1 on 2022-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('documents', models.TextField(max_length=200)),
                ('history', models.CharField(max_length=100)),
                ('rented_since', models.DateField()),
                ('rented_to', models.DateField()),
                ('renewal_date', models.DateField()),
            ],
        ),
    ]
