# Generated by Django 3.1 on 2022-04-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('property_linked_to', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=100)),
                ('documents', models.CharField(max_length=200)),
                ('bank_details', models.CharField(max_length=200)),
                ('history', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.client'),
        ),
    ]
