# Generated by Django 3.1 on 2022-04-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20220411_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'propertie'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='client',
        ),
        migrations.AddField(
            model_name='property',
            name='total_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rented_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.client'),
        ),
    ]
