# Generated by Django 3.1 on 2022-04-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20220412_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'property'},
        ),
        migrations.AlterField(
            model_name='property',
            name='rented_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.client'),
        ),
    ]
