# Generated by Django 3.1 on 2022-04-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20220425_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rented_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.client'),
        ),
    ]
