# Generated by Django 3.1 on 2022-04-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20220425_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rented_to',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='properties.client'),
        ),
    ]
